
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Set up environment
          command: |
            pip3 install --user .
            pip3 install --user pytest
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
      - run:
          name: Level synthesis test 
          command: |
            yes | python3 ./make_level.py testskill testlevel1
            yes | python3 ./make_level.py testskill testlevel2
     - run:
          name: Running tests
          command: |
            export PATH=$PATH:$HOME/.local/bin
            python3 -m pytest gitgud

