
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: python3 -m pip install .
      - run: python3 -m pip install pytest
      - run:
          name: Running tests
          command: python3 -m pytest .