
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Set up environmetn
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
            pip install pytest
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest .